// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://romouirjhrpetvvaitgb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJvbW91aXJqaHJwZXR2dmFpdGdiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkzMjA0NTQsImV4cCI6MjA2NDg5NjQ1NH0.CiYbINr12LkuVeR_yYRhsCKe-WL2SN0PGe5kHFoO4vU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);